version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_DB_CONNECTION_STRING=mongodb://mongo:27017
      - DATABASE_NAME=school
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/MongoDBService

volumes:
  mongo_data: