version: "3.9"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"  # Map port 8010 on the host to port 8010 in the container
    environment:
      - HOST=0.0.0.0
      - PORT=8010
    volumes:
      - .:/app  # Mount the current directory into the container for development